[tool]
[tool.poetry]
name = "root"
version = "0.0.0"

[tool.poetry.dependencies]
python = "*"
pygithub = "==1.45"
python-dotenv = "==0.10.3"
telegram = "==0.0.1"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
